# Site Settings

title: My Great New Blog

author:
  name: Fowad Ijaz
  email: fowad.ijaz@gmail.com
  
description: "My new website"

# Build Settings
remote_theme: jekyll/minima

  

theme: jekyll-theme-cayman
